### ISSUE TITLE
Is there any ref ? I'm also study in Heterogeneous mult-agent Rl,I didn't find any relevant references

### ISSUE THREAD

**Issue by hit-JB** [JacopoPan/gym-marl-reconnaissance#1]

**Comment by JacopoPan** [comment]
Hello @hit-JB 

this repo is still WIP, if you want to look at more mature projects (with corresponding publications) you can also look at the other projects of [DSL](https://github.com/utiasDSL):
- https://github.com/utiasDSL/gym-pybullet-drones
- https://github.com/utiasDSL/safe-control-gym
