### ISSUE TITLE
How much time it costs when training?

### ISSUE THREAD

**Issue by Tie-1** [JacopoPan/gym-marl-reconnaissance#3]
hello @JacopoPan ! Thanks for your public work! I would like to ask if the training time for this job is about how long. I will use the A2C algorithm in about a minute and wonder if there will be any errors?

**Comment by JacopoPan** [comment]
Hello @Tie-1 

I do not have the logs right now but the [results in the `README.md`](https://github.com/JacopoPan/gym-marl-reconnaissance#results) should take relatively little training time (in the order of hours).

**Comment by Tie-1** [comment]
Thank you ! I found out that the problem is due to the setting of total_timesteps.
